#!/usr/bin/env bash
sed 's/127\.0\.0\.1/127\.0\.0\.2/g' /etc/hosts > /tmp/hosts_tmp
cat /tmp/hosts_tmp > /etc/hosts

if grep -q "facebook.com" /etc/hosts; then
    sed 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts > /tmp/hosts_tmp
    cat /tmp/hosts_tmp > /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi

rm -f /tmp/hosts_tmp
